import React from 'react'

export default function TermsPage() {
  return (
    <div className="min-h-screen text-slate-200" style={{ background: '#030712' }}>
      {/* Top Navigation */}
      <header className="sticky top-0 z-50 border-b backdrop-blur-md" style={{ background: 'rgba(7, 17, 31, 0.85)', borderColor: 'rgba(56, 189, 248, 0.16)' }}>
        <div className="max-w-4xl mx-auto px-5 h-16 flex items-center justify-between">
          <a
            href="/"
            className="flex items-center gap-2 text-xs font-mono font-medium text-cyan-400 hover:text-cyan-300 transition-colors"
          >
            <span>←</span>
            <span>Back to SatQuery AI</span>
          </a>
          <nav className="flex items-center gap-4 text-xs font-mono">
            <a href="/privacy" className="text-slate-400 hover:text-slate-200 transition-colors">
              Privacy Policy
            </a>
            <span className="text-slate-600">·</span>
            <span className="text-slate-400 font-semibold">Terms & Conditions</span>
          </nav>
        </div>
      </header>

      {/* Main Content */}
      <main className="max-w-4xl mx-auto px-5 py-12 sm:py-16">
        <div className="mb-10 pb-6 border-b" style={{ borderColor: 'rgba(56, 189, 248, 0.16)' }}>
          <div className="inline-block text-[10px] font-mono tracking-widest uppercase mb-3 px-2.5 py-1 rounded" style={{ color: '#20D9FF', background: 'rgba(32, 217, 255, 0.08)', border: '1px solid rgba(56, 189, 248, 0.24)' }}>
            Legal Terms
          </div>
          <h1 className="text-3xl sm:text-4xl font-bold text-slate-100 mb-3" style={{ fontFamily: "'Space Grotesk', sans-serif" }}>
            Terms & Conditions
          </h1>
          <p className="text-xs font-mono text-slate-400">
            Last Updated: September 17, 2026
          </p>
        </div>

        <div className="space-y-10 text-sm leading-relaxed text-slate-300">
          {/* Section 1 */}
          <section className="space-y-3">
            <h2 className="text-lg font-bold text-slate-100" style={{ fontFamily: "'Space Grotesk', sans-serif" }}>
              1. Acceptance and Scope
            </h2>
            <p>
              By accessing or using the SatQuery AI web application, you agree to be bound by these Terms & Conditions. If you do not agree to these terms, you should immediately discontinue use of the application.
            </p>
          </section>

          {/* Section 2 */}
          <section className="space-y-3">
            <h2 className="text-lg font-bold text-slate-100" style={{ fontFamily: "'Space Grotesk', sans-serif" }}>
              2. Permitted Use
            </h2>
            <p>
              Users may use SatQuery AI for lawful analysis, research, education, testing, and demonstration purposes. You agree to interact with the platform in compliance with all applicable local, national, and international laws and regulations.
            </p>
          </section>

          {/* Section 3 */}
          <section className="space-y-3">
            <h2 className="text-lg font-bold text-slate-100" style={{ fontFamily: "'Space Grotesk', sans-serif" }}>
              3. User-Submitted Content
            </h2>
            <p>
              Users are solely responsible for having the necessary rights, titles, licenses, and permissions to upload imagery and submit text queries to the service. You must not upload imagery that infringes third-party intellectual property rights, violates confidentiality obligations, or compromises legal restrictions.
            </p>
          </section>

          {/* Section 4 */}
          <section className="space-y-3">
            <h2 className="text-lg font-bold text-slate-100" style={{ fontFamily: "'Space Grotesk', sans-serif" }}>
              4. AI and Remote-Sensing Output
            </h2>
            <p>
              All responses, bounding coordinates, building counts, land-classification percentages, change-detection summaries, and optical-SAR metrics generated by the platform are machine-generated analytical estimates. These outputs may be incomplete, inaccurate, or affected by sensor resolution and atmospheric anomalies.
            </p>
            <div className="p-4 rounded-xl border border-amber-500/30 bg-amber-500/10 text-amber-200 text-xs leading-relaxed space-y-1">
              <strong className="block text-amber-100 font-semibold">Independent Review Required:</strong>
              <p>
                Outputs should be independently reviewed and verified by qualified professionals before being used in decisions involving human safety, disaster mitigation, property management, engineering, legal determinations, or other consequential actions.
              </p>
            </div>
          </section>

          {/* Section 5 */}
          <section className="space-y-3">
            <h2 className="text-lg font-bold text-slate-100" style={{ fontFamily: "'Space Grotesk', sans-serif" }}>
              5. No Guaranteed Accuracy
            </h2>
            <p>
              SatQuery AI does not provide any guarantee regarding analytical accuracy or precision. Specifically, the service does not guarantee:
            </p>
            <ul className="list-disc list-inside space-y-1.5 pl-2 text-slate-300">
              <li>Exact building footprint counts or geometric polygon delineations</li>
              <li>Guaranteed visual question answering (VQA) correctness across arbitrary scenes</li>
              <li>Guaranteed change detection attribution or precise boundary coregistration</li>
              <li>Guaranteed optical-SAR cross-modal alignment accuracy</li>
              <li>Benchmark-level performance for every uploaded scene or sensor format</li>
            </ul>
          </section>

          {/* Section 6 */}
          <section className="space-y-3">
            <h2 className="text-lg font-bold text-slate-100" style={{ fontFamily: "'Space Grotesk', sans-serif" }}>
              6. Service Limits
            </h2>
            <p>
              Usage may be subject to session and infrastructure limits, including rate-limiting thresholds, concurrent call limits, file size restrictions, and operational session caps designed to maintain platform stability and protect computational resources.
            </p>
          </section>

          {/* Section 7 */}
          <section className="space-y-3">
            <h2 className="text-lg font-bold text-slate-100" style={{ fontFamily: "'Space Grotesk', sans-serif" }}>
              7. Availability
            </h2>
            <p>
              The application and its associated endpoints are provided on an "as is" and "as available" basis. The service may be temporarily unavailable, modified, throttled, or discontinued at any time without prior notice.
            </p>
          </section>

          {/* Section 8 */}
          <section className="space-y-3">
            <h2 className="text-lg font-bold text-slate-100" style={{ fontFamily: "'Space Grotesk', sans-serif" }}>
              8. Prohibited Use
            </h2>
            <p>
              When using SatQuery AI, you agree not to engage in:
            </p>
            <ul className="list-disc list-inside space-y-1.5 pl-2 text-slate-300">
              <li>Any activity that violates applicable laws or regulations</li>
              <li>Attempts to gain unauthorized access to backend systems, infrastructure, or other users' data</li>
              <li>Abuse, intentional overloading, or denial-of-service attempts against service APIs</li>
              <li>Circumvention of rate limits, session call limits, or operational constraints</li>
              <li>Uploading malicious payloads or content without appropriate authorization</li>
            </ul>
          </section>

          {/* Section 9 */}
          <section className="space-y-3">
            <h2 className="text-lg font-bold text-slate-100" style={{ fontFamily: "'Space Grotesk', sans-serif" }}>
              9. Third-Party Services
            </h2>
            <p>
              The application may depend on configured backend microservices, model runtimes, or external inference providers to process analysis requests. Availability and latency may vary based on upstream service health.
            </p>
          </section>

          {/* Section 10 */}
          <section className="space-y-3">
            <h2 className="text-lg font-bold text-slate-100" style={{ fontFamily: "'Space Grotesk', sans-serif" }}>
              10. Intellectual Property
            </h2>
            <p>
              Users retain responsibility for and rights in the imagery and text content they upload. SatQuery AI does not assert ownership over user-submitted satellite imagery or user-generated analysis prompts.
            </p>
          </section>

          {/* Section 11 */}
          <section className="space-y-3">
            <h2 className="text-lg font-bold text-slate-100" style={{ fontFamily: "'Space Grotesk', sans-serif" }}>
              11. Changes to Terms
            </h2>
            <p>
              These Terms & Conditions may be modified as the application, its underlying models, or its service structure evolve. Continued use of the application following the posting of updated terms constitutes acceptance of those revisions.
            </p>
          </section>

          {/* Section 12 */}
          <section className="space-y-3">
            <h2 className="text-lg font-bold text-slate-100" style={{ fontFamily: "'Space Grotesk', sans-serif" }}>
              12. Contact
            </h2>
            <p>
              For project or data-handling questions, use the contact channel provided in the application.
            </p>
          </section>
        </div>

        {/* Bottom Navigation */}
        <div className="mt-16 pt-8 border-t flex flex-col sm:flex-row items-center justify-between gap-4 text-xs font-mono text-slate-400" style={{ borderColor: 'rgba(56, 189, 248, 0.16)' }}>
          <a href="/" className="text-cyan-400 hover:text-cyan-300 transition-colors">
            ← Back to SatQuery AI
          </a>
          <div className="flex items-center gap-4">
            <a href="/privacy" className="hover:text-slate-200 transition-colors">
              Privacy Policy →
            </a>
          </div>
        </div>
      </main>
    </div>
  )
}
